[tox]
envlist =
    py{312, 313}-buildhtml
    forcedphot
    fornaxtest
requires =
    pip >= 19.3.1

[testenv]

description = run tests and build html

passenv = CI, CIRCLECI, GITHUB_EVENT_NAME, GITHUB_EVENT_PATH, BASE_URL

system_site_packages =
    forcedphot: True
    fornaxtest: True

deps =
    # Notebook infrastructure requirements
    -rgeneric_requirements.txt
    # pytest testing requirements
    !buildhtml: -rtest_requirements.txt
    # Notebook content dependencies, we install it here for the HTML builds, pytest uses the fornax docker image
    buildhtml: -rcrossmatch/requirements_ztf_ps1_crossmatch.txt
#   buildhtml: -rforced_photometry/requirements_multiband_photometry.txt
#   buildhtml: -rlight_curves/requirements_light_curve_collector.txt
    buildhtml: -rlight_curves/requirements_scale_up.txt
    buildhtml: -rlight_curves/requirements_light_curve_classifier.txt
    buildhtml: -rlight_curves/requirements_ML_AGNzoo.txt
    buildhtml: -rspectroscopy/requirements_spectra_collector.txt
    # We use these files to specify all the dependencies, and below we override
    # versions for specific testing scenarios
    buildhtml: -rsite-requirements.txt


allowlist_externals =
    bash

commands =
    jupyter kernelspec list

    # For now we only use the fornax kernels on GHA and pytest;
    # This is hard wired and only work for GHA, TODO: control these with an env variable and/or other conditionals
    !buildhtml: bash -c 'for kernel in $(ls /usr/local/share/jupyter/kernels |grep py-); do jupyter kernelspec install /usr/local/share/jupyter/kernels/$kernel; done'
    pip freeze
    jupyter kernelspec list

    # Ignore some notebooks for various types of testing. The individual lists are stored in the `ignore_tutorials`
    # directory and are documented about the specific reasons of them included in the ignores.
    # These files are kept under version control.
    # The files `ignore_testing` and `ignore_execution` are generated during the CI jobs and are not under version control.

    # Making sure the ignore files we use always exist
    bash -c 'touch ignore_testing'

    buildhtml: bash -c 'cat ignore_tutorials/ignore_rendering_execution >> ignore_testing'
    buildhtml: bash -c 'if [[ $CIRCLECI == true ]]; then cat ignore_tutorials/ignore_circleci_testing >> ignore_testing; fi'

    # Make a list of all the tutorials to be reused in multiple filtering commands below
    bash -c "grep md deployed_notebooks_manifest.in | xargs grep name: | awk  -F : '{print $1}' | uniq > all_tutorials"

    # Make a list of the tutorials changed, we only need this in CI. Also deal with grep's non-zero exit code.
    bash -c 'if [[ $CI == true ]]; then git fetch origin main --depth=1; git diff origin/main --name-only | (grep ".md" || true); fi > changed_tutorials'

    # We need to override the kernelspec name field until
    # https://github.com/jupyter-book/mystmd/issues/2302 is resolved
    buildhtml: bash -c "cat all_tutorials | xargs grep name: | awk  -F : '{print $1}' | uniq | xargs -n 1 sed -i -Ee 's|(^\s*)(name:)(.*)|\1name: python3|g'"

    # We don't want to execute in rendering the ones we ignore for testing
    buildhtml: bash -c '(grep -f ignore_testing all_tutorials || true) > ignore_execute'

    # On CircleCI rendering preview, we also don't want to execute anything that hasn't been modified
    buildhtml: bash -c 'if [[ $CIRCLECI == true ]]; then (grep -vf changed_tutorials all_tutorials || true) >> ignore_execute; fi'

    # sed -i needs a bit of hacky conditional on ubuntu to cover the case of an empty ignore
    buildhtml: bash -c 'if [ -s ignore_execute ]; then for name in $(cat ignore_execute | sort| uniq); do if [ -z "$(head -n 20 ${name}| grep execute:)" ]; then sed -i -e "s|kernelspec:|execute:\n  skip: true\nkernelspec:|g" ${name}; fi; done;fi'

    buildhtml: bash -c "echo 'Notebooks ignored (not tested/executed) in this job:'; cat ignore_execute | sort | uniq"

    buildhtml: bash -c "jupyter-book build --execute --html --strict -d"

    # We only skip testing untouched tutorials in PRs; in cron and dispatch all should be tested.
    # Also, making sure we don't jupytext non-notebook files.
    fornaxtest: bash -c 'if [[ $GITHUB_EVENT_NAME == pull_request && -z "$(grep force_run:all_tests ${GITHUB_EVENT_PATH})" ]]; then grep forced_photometry changed_tutorials; else grep forced_photometry all_tutorials; fi | grep -vf ignore_testing | xargs jupytext --to notebook '

    fornaxtest: pytest --nbval-lax -vv --suppress-no-test-exit-code --durations=10 forced_photometry/

skip_install = true
