version: 2.1

jobs:

  build-docs:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Install mystmd
          command: |
            npm install mystmd

      - run:
          name: Install Python dependencies
          command: |
            python -m pip install --upgrade pip tox

      - run:
          name: Build HTML rendering of notebooks
          no_output_timeout: 60m
          environment:
            # Ensure this is same as store_artifacts path below
            DOCS_PATH: _build/html
          command: |
            export BASE_URL="/output/job/$CIRCLE_WORKFLOW_JOB_ID/artifacts/0/$DOCS_PATH"
            export OMP_NUM_THREADS=1
            python -m tox -e py312-buildhtml

      - store_artifacts:
          path: _build/html

workflows:
  version: 2
  build-and-docs:
    jobs:
      - build-docs
