wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.3
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721192029.8704
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 3
      - 13
      - 23
      4: 3.7.3
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
