name: Fornax image tests

on:
  pull_request:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  forcedphot:
    # Do not run the test matrix on PRs affecting the rendering
    if: >-
      (!(github.event_name == 'pull_request') || !contains(github.event.pull_request.labels.*.name, 'html rendering / skip testing')) &&
      github.repository == 'nasa-fornax/fornax-demo-notebooks'

    name: Testing forced photometry
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nasa-fornax/fornax-images/fornax-main:stable

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install test dependencies
        run: python -m pip install --upgrade tox

      - name: Test with tox
        run: tox -e forcedphot
